require:
  - beet.contrib.inline_function
  - beet.contrib.inline_function_tag
  - beet.contrib.template_context
  - beet.contrib.dundervar

pipeline:
  - base.plugins.other.globals
  - base.plugins.lantern_load
  - base.plugins.advancements
  - base.plugins.other.function_headers
  - beet.contrib.render
  - beet.contrib.hangman
  - beet.contrib.yellow_shulker_box


data_pack:
  name: "{{ctx.project_name}} v{{ctx.project_version}}"
  load:
    - .

meta:
  render:
    data_pack:
      functions:
        - '*'
  hangman:
    match:
      - '*'
 
